const words = [
//list 1
`
abase,降低地位、尊严,,
abash,使尴尬、羞愧,,
abate,减轻,减少,停止
abdicate,放弃责任、权利,,
aberrant,异常的,,
abet,帮助、怂恿,,
abeyance,中止、搁置,,
abhor,深恶痛绝,
abiding ,持久的,永久的,
abject,凄惨的,卑微的,糟糕的
abjure,发誓放弃,抵制,避免
abnegate,放弃,否认,投降
abominate,憎恶,,
aboveboard,光明正大的,,
abrade,刮擦磨损,精神折磨,
abrogate,官方废除,取消,抛开
abscond,偷偷离开,,
absolve,使无罪,解除责任,
abstain,自我节制,主动戒绝,
abstemious,吃喝节制/节俭的,,
abstruse,难以理解的,,
abut,毗邻,,
abysmal,极可怜的,极端的,
accede,同意,入职,正式加入
acclimate,使适应,,
accolade,赞扬,同意,
accost,挑衅的搭讪,,
accrete,逐渐增长,,
acerbic,酸涩的,,
acme,顶点,绝佳典范,
acquiesce,勉强同意,默许,
acrid,辛辣刺鼻的,刻薄的,
acrimonious,刻薄的,充满仇恨的,
acumen,敏锐的洞察力,,
adamant,固执的,,
acute,严重的,敏锐的,急性的
adjourn,延期、休会,,
adjunct,附属品,非必需部分,
ad-lib,即兴的,,
admonish,责备,建议,
adulate,极度谄媚,,
adulterate,参杂,,
adumberate,有保留的揭露,,
adventitious,外来的,后天的,
advert,引起注意,提到,
aggrandize,提高（财富、地位、声誉）,,
aggravate,恶化,使不爽,
aggrieve,使悲痛,使苦恼,
agitate,煽动,使不安,
agog,极度感兴趣,,
agonize,使非常痛苦,,
airtight,密封的,无瑕疵的,
alibi,不在场证明,托辞,
allay,减轻,,
allegiance,忠诚,,
allude,提及,暗指,
aloft,在空中,,
aloof,孤高的,不合群的,
altruism,利他主义,,
amalgamate,合并、混合,,
amble,漫步、闲逛,,
ambrosial,特别美味的,,
amenable,顺从、服从的,,
amenity,舒适、人性化,,
amicable,amiable,amity,友好和善的
`,
//list 2
`
amorphous,无固定形状的,不可归类的,,,,
analgesic,止痛剂,,,,,
anestehetic,止痛剂,麻木的,,,,
anarchist,反对权威者,,,,,s
anathema ,诅咒,,,,,
anacillary,次要的,辅助补充的,,,,
anemic,缺乏活力的,,,,,
animate,活的,有活力的,驱使,,,
animus,敌意,,,,,
annul,取消,抵消,,,,
anomalous,不正常的,不寻常的,,,,
antagonize,敌对反对,激起敌意,,,,
antediluvian,过时的,极古老的,老古董,,,
anterior,先前的,,,,,
antic,滑稽可笑的,,,,,
apathy,冷漠的,不关心的,,,,
apocalyptic,预言的,转折点的、重要的,,,,
apocryphal,假的,,,,,
apoplectic,盛怒的,,,,,
apostasy,放弃宗教信仰,背叛、变节,,,,
appall,使惊恐,,,,,
apposite,相关的,合适的,,,,
appreciable,可感知的、明显的,,,,,
apprehension,有‘恐惧、忧虑’、‘逮捕’之意,,,,,
apprise,通知告知,,,,,
appropriate,有‘私自挪用’之意,,,,,
apropos,相关的,关于,,,,
apt,合适的,有。。倾向,聪明的,,,
archetype,典范,原型,鼻祖,,,
arduous,费力的,险峻的,,,,
approbation,同意,,,,,
argot,隐语、黑话,,,,,
arrest,使不活泼,停止,吸引注意力,,,
arresting,吸引人的,,,,,
arrhythmic,不规律的,,,,,
articulate,清楚的表达,,,,,
ascendant,有‘主导地位’之意,,,,,
ascetic,禁欲的,,,,,
aspetic,无菌的,缺活力的,冷漠的,,,
askew,歪的,,,,,
asperity,粗暴,（环境）艰苦,,,,
asperison,诽谤、中伤,,,,,
aspirant,有抱负的人,,,,,
assent,同意,,,,,
assertive,武断的,强烈自信的,,,,
assiduous,勤勉的,专心仔细的,,,,
astounding,令人吃惊的,,,,,
astute,敏锐的,有洞察力的,,,,
asunder,分成碎片的,分离,,,,
asylum,收容/保护所,,,,,
atone,赎罪,弥补,,,,
atrocious,极坏的,极不满意的,,,,
attenuate,降低,,,,,
audacious,大胆的,冒险的,愚勇的,,,
augur,预言,预言家,,,,
autocracy,独裁政府,,,,,
avarice,贪婪贪财的,,,,,
aver,强硬声明,,,,,
avid,急切渴望的,贪财的,,,,
awash,淹没的,泛滥的,,,,
awning,遮阳篷,雨棚,,,,
awry,弯曲,出差错,,,,
axiomatic,公理的,不言自明的,,,,
babble,嘟囔,闲聊,,,,
badger,不断纠缠骚扰,,,,,
badinage,打趣、善意的玩笑,,,,,
bait,逗弄,激怒,,,,
bale,痛苦,悲哀,,,,
baleful,有害的,凶恶的,,,,
balk,阻碍,拒绝,,,,
balky,倔强的,,,,,
balled,歌谣民谣,,,,,
balloon,有‘激增’之意,,,,,
balm,香气、香油,止痛膏,,,,
banal,平庸陈腐的,,,,,
bane,毒药,祸根,,,,
banter,玩笑、逗乐 ,bait,,,,
`,
//list 3
`
barb,严厉的批评,,,
barefaced,公然的,厚颜无耻的,,
barrage,弹幕,火力攻击,同时袭来,
barren,不育的,无效的,贫瘠的,
barricade,障碍物,设障,,
bathetic,平凡的,陈腐的,,
bawdy,下流猥亵的,,,
bedeck,装饰、点缀,,,
belabor,责骂,唠叨,,
beleguer,围攻,困扰,,
belie,掩饰,证明。。。为假,与。。矛盾,误述
bellwether,领头人,,,
berate,严责、申斥,,,
beseech,恳求,,,
besmirch,弄脏,玷污,,
bifurcate,分成两支,分歧,,
bigot,固执己见者,有偏见的人,,
blend,无味的,冷漠的,温和的,
blandishment,奉承,讨好,,
blasé,倦于享乐的,玩厌的了,,
blatant,炫耀的,喧嚣的,公然的,
blazon,广布,宣布,装饰,
blemish,有损。。完美,瑕疵,污点,
blight,枯萎 ,损害,,
bliss,极乐,狂喜,,
blithe,愉快无忧的,,,
blunder,过失,蹒跚,,
blurt,脱口而出,,,
bluster,咆哮,威吓,狂吹,
boggle,（因怀疑恐惧）迟疑犹豫,,,
boisterious,喧嚷的,,,
bombast,夸大的言辞,,,
bonhomie,温和、和蔼,,,
boo,嘘声、喝倒彩,,,
boor,粗野的人、农民,,,
bootless,无用的,无利可图的,,
bracing,令人振奋的,支撑,紧固装置,
brash,仓促性急的,鲁莽无礼的,,
brassy,厚脸皮的,俗艳的,,
bravado,虚张声势,假装勇敢,,
bravura,高潮演奏技巧,大胆尝试,,
brazen,大胆（自信）,蛮横无礼的,,
breach,违反,破坏,,
brevity,简洁,,,
bridle,限制,约束,,
brisk,生机活力的,刻薄的,,
bristle,刚毛、猪鬃,发怒,供应充足,
brittle,易碎的,不真心的,,
broach,给。。开口,钻孔,开始讨论,
bromide,陈词滥调,,,
brook,容忍,小溪流,,
browbeat,威逼恫吓,,,
bruit,散播,谣传,,
buck,雄性动物,组织反对,转移交接,
budge,改变立场,让步,,
bulge,凸起,肿胀,鼓出,充满
bumptious,傲慢自大的,,,
bungle,办糟,失败,,
buoy,浮标,支撑 ,鼓励,
buoyant,有浮力的,心情轻快的,,
burgeon,发芽抽枝,迅速发展,,
burlesque,滑稽模仿,,,
butnish,擦亮,磨光,,
buttress,支撑物,支持的证据,,
byzantine,有‘错综复杂’之意,,,
cachet,同意,（认证）标志,声望,
cacophony,刺耳的声音,,,
cadge,乞讨乞求,,,
cajole,（甜言蜜语）哄骗,,,
calcify,钙化,使僵化,,
calligraphy,美术字体,书法,,
callous,无情冷漠的,起老茧的,,
callow,年轻无经验的,不成熟的,,
cameo,客串,生动描述,刻画,
camouflage,伪装,,,
canard,谣传,bruit,,
candor,坦白,诚挚,bluntness,
canon,标准,教规,真经,
`,
//list 4
`
canvass,细察,讨论,游说,
capitulate,投降,默许,,
caprice,反复无常,善变,一时冲动的决定,
careworn,忧心焦虑的,,,
cardinal,主要基本的,鲜红色,,
caricature,漫画,讽刺画,,
carnal,肉体的,世俗的,淫荡的,性欲的
carouse,畅饮,狂欢作乐,,
carp,吹毛求疵,找茬儿,cavil,
castigate,强烈公开谴责,惩罚,,
categorical,绝对的,无条件的,明确的,
catholic,普遍的,包容的,天主教的,
caustic,腐蚀的,刻薄挖苦的,,
caveat,警告告诫,,,
cavil,,,,
cavort,欢跃,,,
cement,水泥,粘合剂,巩固加强,
censorious,挑剔指责的,,,
censure,公开反对,谴责,,
cessation,终止,暂停,,
chaff,打趣逗弄,无价值的东西,,
banter,badinage,打趣逗乐,,
chagrin,懊恼,气愤,委屈,
chameleon,变色龙,善变的人,,
champion,有‘支持拥护’之意,,,
charade,装模作样,动作字谜,,
charlatan,骗子,吹牛者,江湖医生,
chary,谨慎的,节省的,,
chasm,分歧,裂口,峡谷,
check,有‘阻止‘、’同意‘、’一致‘之意,,,
cherubic,可爱的,天使的,,
chide,责骂,belabor,berate,
choleric,易怒的,暴躁的,,
chord,和谐,符合,和弦,
chromatic,有色彩的,鲜艳的,,
churl,粗野的人,吝啬鬼,,
cipher,无影响/无价值的人,计算（价值）,密码,
circuitous,不直接的,迂回的,绕行的,冗长的
circumlocution,冗长,绕圈子的话,,
circumspect,谨慎小心的,,,
circumvent,躲避,不遵从,,
clandestine,隐秘的,,,
clarion,清楚响亮的,a clarion call,,
clasp,紧握,,,
clement,宽容善良的,气候温和的,,
cliché,陈词滥调,bromide,,
clog,阻碍/阻碍物,堵塞,,
clot,密集的,堵塞,一群,凝结
clout,权力,影响力,,
cloying,（食物/感情）甜腻的,,,
coagulate,凝结,使变稠,,
coalesce,合并,融合,,
coax,哄骗,cajole,blandish,
coda,终曲,,,
coerce,强迫,武力压制,,
cogent,令人信服的,相关的,,
cognizant,意识到的,察知的,,
collude,串通,共谋做坏事,,
colossal,巨大的,,,
coltish,活蹦乱跳的,马驹似的,不守纪律的,爱开玩笑的
combustible,可燃的,容易激动的,,
comely,漂亮的,,,
comity,友好,社会和谐,,
commensurate,相等相当的,,,
commingle,充分混合,,,
compendium,摘要、刚要,,,
compendious,简洁全面的,,,
commodious,宽敞的,,,
commotion,骚乱,,,
complacency,自满,无忧患意识,,
complaisance,愿意顺从讨好的,彬彬有礼的,,
compose,使镇静,组成,,
`,
//list 5
`
compound,有‘扩大增多’‘和解’之意,,,,
compunction,内疚,懊悔,,,
concatenate,连结,混合,,,
concerted,共同筹划的,合作的,,,
conciliate,平息,抚慰,调解,,
concord,一致,和睦,,,
concur,同意,同时发生、存在,团结合作,,
condescending,高人一等的姿态,屈尊的,,,
condign,应得的,恰当的,,,
condole,表达同情,,,,
condone,宽恕,忽视,,,
conducive,有益的,,,,
confine,禁闭,监禁,限制,,
confluence,汇合混合,直接对抗、直面,,,
confound,使困惑,无法区分、混淆,证明。。为假,,
congeal,凝固,固化,,,
congenial,和善友好的,令人愉悦的,,,
congruent,全等的,和谐一致的,,,
conjecture,揣测的结果,猜测估计  ,,,
connive,共谋,默许,纵容,,
connoisseur,鉴赏家,专家,,,
conscientious,仔细的、一丝不苟的,有良心的,,,
conservatory,温室,艺术学院,,,
console,安慰,慰藉,,,
consonant,一致符合的,和谐的,,,
conspicuous,显而易见的,吸引人的,,,
conspire,合谋,密谋,contrive,connive,intrigue
constitute,有‘指派、任命‘之意,,,,
constringe,使紧缩,,,,
consummate,专业的,有造诣的,完美的,最高档次最大规模的,
contagious,传染的,引起共鸣的,,,
contentious,引起争论的,好争论好战的,,,
contiguous,接壤的,,,,
contort,扭曲,,,,
contravene,违反、反对,,,,
contrite,悔罪的,,,,
contumacious,不服从的,倔强的,balky,,
conundrum,无法解决的问题,谜,,,
convalesce,渐愈,,,,
conversant,熟悉的,,,,
conviction,深信,证明有罪,,,
convoke,召集开会,,,,
convulsion,痉挛,骚乱,,,
coop,监禁,困于。。之中,confine,,
copious,丰富的,大量的,,,
coquette,调情,卖弄风情的女人,,,
cordon,警戒线,用警戒线包围隔离,,,
cornucopia,大量（n）,,,,
coronation,加冕,加冕礼,,,
corporeal,肉体的,有形的、实体的,,,
corroborate,证实,提供证据、支持,,,
corrosive,腐蚀性的,讽刺性的,,,
corrugated,褶皱的,,,,
cosmopolitan,世界性的,包容的,cosmopolitism,,
cosset,宠爱,,,,
countenance,容忍,赞成、推崇,沉着冷静,,
countermand,取消撤销,annul,,,
court,有‘献殷勤、求爱’之意,,,,
covetous,贪财的,acquisitive,avaricious,avid,
covet,垂涎觊觎,,,,
cow,恐吓威吓,,,,
cowardice,懦弱、不坚定,coward 懦夫,,,
cower,畏缩,,,,
cozen,诱骗,,,,
cramped,狭促的,,,,
crass,粗俗的,愚钝的,,,
crave,恳求,渴望,,,
craven,怯懦的,懦夫,,,
crease,折痕,,,,
credence,坚信,,,,
credulous,轻信的,易受骗的,,,
`,
//list 6
`
crescendo,（声音）渐强,顶峰,crest
crest,顶部,浪尖,
crestfallen,垂头丧气的,,
cronyism,任人唯亲,,
crook,使弯曲,,
croon,低声唱歌或说话,,
crouch,蹲伏,,
crumple,弄皱,crease,垮塌
crutch,支撑、支柱,,
crux,中心,关键点,
cryptic,秘密的,含义模糊的,超出理解能力的
culpable,该受谴责的,有罪的,
curmudgeon,坏脾气的人,守财奴,
cursory,匆忙的,不注意细节的,
curt,简要以致粗鲁的,言简意赅的,
curtail,缩短,削减,
cynic,愤世嫉俗者,,
dabble,浅的涉猎,,
daft,神经错乱的,不明智的,
dais,主席台,嘉宾席,
dally,虚度时光,玩乐,磨蹭
damper,抑制因素,,
dandy,纨绔子弟,上好的,
dank,阴湿的,,
dapper,衣冠整洁的,,
dappled,有斑点的,色彩斑斓的,
daredevil,冒失鬼,大胆鲁莽不顾后果的,
dart,突然移动,公开侮辱,
dawdle,闲荡、虚度光阴,拖拉,
deadpan,无动于衷,无表情的脸,
dearth,缺乏,,
debacle,溃败,,
debark,从船上飞机上卸货,,
debase,贬低贬损,,
debilitate,使衰弱,,
debris,废墟,,
debunk,揭穿真相,证明为假,
debut,初次登台,,
decant,轻轻倒出,,
decorum,礼仪,得体,
decrepit,虚弱的,衰老的,
default,有‘拖欠债务’之意,,
defile,亵渎,狭路,污染弄脏
deft,灵巧熟练的,,
defuse,抚慰、减轻,,
defy,反抗、违抗,,
dehydrate,去除水分,使失去活力或味道,
deify,尊敬遵从,过分喜爱,神
deleterious,有害的,baleful,baneful
delicacy,精致,,
delirium,精神错乱,,
delusion,错觉,,
deluge,大暴雨,大量,
delve,探究钻研,,
demagogue,煽动政治家,,
demolition,破坏毁坏,,
demotic,通俗的、大众化的,,
demur,反对,犹豫,
denigrate,诋毁,污蔑,
denouement,（小说的）结局,,
dent,凹陷,使变小变弱,
denuded,脱去,使赤裸,
deplore,哀悼,,
deportation,放逐,,
depose,发誓作证,废黜罢免,摆放
depravity,道德败坏,,
deprecate,不赞成、反对,贬低,使低调
depreciate,有‘轻视’之意,,
deprivation,匮乏,,
deracinate,根除,,
derelict,玩忽职守的,被社会抛弃的,
deride,嘲弄,,
derivative,非原创的,,
desecrate,玷污亵渎,,
desiccate,弄干、使脱水,使缺乏活力,
designate,任命,命名,
`,
//list 7
`
despicable,令人鄙视的,不荣耀不得体的,,
despise,鄙视轻视,极其不喜欢,,
despotic,专制的,暴虐的,,
desultory,无计划无目的的,令人失望的,,
detain,拘留,,,
detour,偏离正常标准,改变方向或路线,,
detract,贬低,使分心,,
detritus,废品,碎屑,遗骸,
dexterous,动作灵活的,头脑灵活的,,
diabolic,恶魔一般的,,,
diaphanous,模糊的,非实在的,（精致的）几乎透明的,
diatribe,长篇抨击性演讲,挖苦讽刺的指责,,
diehard,顽固保守的,,,
diffident,不自信的、内向的,,,
diffuse,有‘啰嗦的’‘不集中的’之意,,,
digress ,脱离主题,,,
dilapidate,使荒废,,,
dilate,使膨胀、扩大,详细表达,,
dilatory,拖延磨蹭的,,,
dilettante,业余爱好者/缺乏专业技术的,,,
din,喧闹声,嘈杂声,重复,
dingy,昏暗的,肮脏的,,
diocesan,主教管辖区的,cosmopolitism,世界主义,
diplomatic,使用策略的,机智的,,
dire,不吉的、不祥的,可怕的,迫切的,悲惨的
dirge,挽歌,,,
disabuse,打消错误念头,纠正,,
disaffect,不满的,叛逆的,,
disarray,混乱无序,,,
discharge,解雇,不承担责任,释放,
disciple,信徒、追随者,,,
discombobulate,使不安,使混乱,,
discomfit,使尴尬,阻碍,,
discommode,打扰、使不便,,,
discompose,使不安,使混乱,,
disconcert,使不安,,,
discord,意见不一致,不和谐,concord,和谐一致
discredit,羞辱,使丧失名誉,不相信,
discrepancy,差异、矛盾,,,
discretion,谨慎,节制自制,,
discretionary,自主决定的,,,
discursive,杂乱的,,,
disdain ,轻视、鄙视,,,
disengage,分开,,,
disgruntle,使不满意,使疏远、不友好,,
disinclination,厌恶、不情愿,,,
disinfect,消毒、使无菌,,,
disinter,（从墓地里）掘出,,,
dismantle,分解、分拆,,,
dismay,使失去勇气,使不安、焦虑,,
disparage,贬低,,,
dispatch,迅速 with dispatch,派遣,使死亡,获胜
dissect,仔细分析,切成片（解剖）,,
dissemble,掩饰,,,
disseminate,散播、传播,,,
dissension,意见不合,,,
dissipate,驱散,浪费,放纵,
dissolute,放荡无节制的,,,
dissonance,不和谐、刺耳,,,
dissuade,劝阻、反对,,,
distal,远离中心的,神经末梢的,,
distend,膨胀,,,
distraught,精神狂乱的,极疯狂的,,
diurnal,白天的,每天的,期刊,
`,
// list8
`
divert,使转向,使消遣,使分心,
divestiture,剥夺,,,
dodder,蹒跚,颤巍的走,,
dodge,躲避,,,
doff,脱下,,,
dogged,坚持的,固执任性的,,
doldrums,低迷,中断,情绪不佳,
dolorous,忧伤的,,,
dolt,笨蛋,,,
domicile,住所、住宅,,,
don,穿上, doff脱下,,
doodle,乱花,打发时光,,
dormant,静止的,冬眠的,,
dour,闷闷不乐、死气沉沉的,,严厉的,
douse,熄灭,弄湿,,
doyen,有经验的人,高级会员,,
drwal,慢吞吞的说,,,
dreary,单调乏味的,令人不悦的,,
drench,浸透、湿透,,,
drivel,胡言乱语,,,
drizzle,毛毛雨,deluge 暴雨,,
droll,古怪有趣的,,,
drone,单调的说,单调的声音,混日子,
drudgery,苦工,单调、卑贱的工作,,
dubious,怀疑的,,,
ductile,可塑的、有延展性的,,易受影响的,
dulcet,悦耳的,令人愉悦的,,
dullard,笨蛋,,,
dupe,复制品,易受骗的人,欺骗,
duplicity,欺骗,表里不一,,
dwindle,逐渐减少,,,
dyspeptic,脾气坏的,消化不良的,dyspepsia 名词消化不良,
earshot,听力所及的范围,,,
earsplitting,震耳欲聋的,,,
eavesdrop,偷听,,,
ebullient,热情奔放的,,,
eccentric,行为出格的,不循规蹈矩的,,
éclat,辉煌成就,,,
eclipse,下降、衰退,使黯然失色、超越,,
ecstasy,无法自控的情绪,,狂喜,
ecumenical,世界范围的、普遍性的,,全球基督教会的,
edifice,大厦、大建筑物,,基础、基本构架,
efface,擦掉、抹去,使不明显,,
effervesce,冒泡,兴奋、热情洋溢,,
effete,衰弱的,缺乏信念、懦弱的,,debilitate 使虚弱
effluvium,难闻的气味,废品,effluvial 恶臭的,
effulgent,光辉灿烂的,,,
effusive,感情横溢的,,,
egoistic,以自我为中心的,,利己的,
elate,使开心自豪,,,
eleemosynary,慈善的,,,
elegy,哀歌、挽歌,,,
elephantine,巨大的,笨拙的,,
elevate,道德、智力、文化水平的提升,,,使兴奋
elliptical,含糊不清的,椭圆的,,
elucidate,阐明,,,
emaciate,使变瘦,使虚弱,,
emancipate,解放,解除束缚,,
embezzle,盗用,,,
emboss,以浮雕效果妆点,,装饰,
embroider,详细说明（带夸张）,,刺绣,
eminent,杰出的,,,
emollient,起缓和作用的,,,
enact,制定颁布法律,,,
enamel,涂亮漆、是具有光泽表面,,给。。上彩饰,
encomium,赞辞,accolade 称赞,panegyric 赞文,
encompass,组成、包含,包围,,
encumber,阻碍妨碍,增加负担,,
endemic,地方性的,,,
enervate,使衰弱,使麻木,debilitate 使虚弱,
enfranchise,给予权利,解放,,
engender,产生、引起,使发展,,
engross,使全神贯注,,,
enigma,谜,,,
`,
// list 9
`
entice,诱使,,,,
entrance,有‘使入迷’之意,,,,
entrap,诱骗,,,,
entreat,恳求,beseech,besiege,,
enunciate,清晰的说,公开宣称,,,
ephemeral,短暂的,evanescent,impermanent,,
epic,宏大的,超凡脱俗的,,,
epicure,美食家,,,,
epigram,机智的短诗,警句,aphorism,proverb,
epilogue,结语、收场白、尾声、后记,,,coda,
epithet,外号绰号,,,,
epitomize,摘要,代表、体现,,,
equable,（性情）温和的,,,,
equivocate,模棱两可的说、说谎话,,,,
errant,居无定所的,误入歧途的、犯错的,,,
erratic,善变的,异常的,,,
erudite,博学的,,,,
escalate,升级、扩大,aggrandize,,,
eschew,刻意避开、戒绝,,abstain,,
esoteric,深奥难懂的,秘传的、少数人知道的,,,
estimable,值得尊敬的,可估计的,,,
estrange,使疏远、离间,,,,
etch,蚀刻,留下深刻印象、铭记,,,
ethereal,轻巧精致的,天国的,精神上的,,
eulogize,称赞、颂扬,encomium,laud,accolade,
euphemism,委婉的说法,,,,
euphoria,极度愉快的心情,,elation,rapture,
evanescent,逐渐消失的、短暂的 ,,,,
evasive,逃避的,含糊其辞的,fugitive,,
evict,赶出,驱逐,,,
evince,表明,,,,
exacerbate,使加剧、使恶化,,,,
exacting,严格的、苛求的,费时间花心思的,,,
exait,提升、提拔,赞扬,elevate,deify,dignify
exasperate,激怒,aggravate,gall,,
excavate,挖掘,,,,
excoriate,严厉批评,berate,,,
excrete,排泄,,,,
excruciate,折磨、使痛苦,agonize,anguish,,
excursive,离题的,散漫的,,,
execrate,谴责,痛恨,abhor/ abominate/ loathe 厌恶,,
exhort,敦促、力劝,,,,
exigent,紧急的,imperative,,,
exodus,大批离去,,,,
exonerate,免除责备,absolve/ acquit,,,
exorbitant,过度的,extravagant,,,
expedite,加快进程,expedition,动作迅速,,
expiate,赎罪、纠正,,,,
exploit,有‘勋绩、功绩’之意,,,,
exponent,有‘倡导者、支持者、实践者’之意,,,,
expurgate,净化、删去不当处,,,,
exquisite,精致敏感细致的,程度强烈的,,,
extant,现存的,,,,
extemporize,即兴创作、即席演奏,,,,
extenuate,减轻、低谷、藐视,,,,
extol,赞美、吹捧,laud/ exalt,,,
extort,勒索,,,,
extraction,血统,,,,
extravagant,挥霍的,过度的、不必要的,,,
extricate,使解脱、救出,解脱者,,,
exuberant,热情洋溢的、非常高兴的,,ebullient/ effervescent/ buoyant/ vivacious,,
exuberant,大量的、充分的,,,,
exude,分泌、流出,,,,
exult,感到欢喜,,,,
fable,寓言、神话传说,谎言,,,
facetious,爱开玩笑的,轻浮的,,,
facile,表面的、浅尝辄止的,,容易的、唾手可得的,,
faction,派系,bloc,coalition,,
fallacious,谬误的、不合逻辑的,,欺骗性的,,
fallow,休耕的,闲置的,,,
fail-safe,保险措施,万无一失的,,,
`,
// list 10
`
falsehood,谎言,mendacity,,,
falter,蹒跚,犹豫、踟蹰,dodder 蹒跚,vacillate 摇摆、犹豫,
fanatic,狂热者,狂热的、盲信的,,,
farce,滑稽戏（嘲讽）,,caricature,,闹剧
fast,绝食、斋戒,fast to death,忠诚的,稳固的、难以拆卸的,
fastidious,挑剔的、极仔细的、追求完美的,,,exacting ,
fateful,意义重大的、灾难性的,,致命的,,
fathom,探测（深度）,彻底理解、弄懂,,,
fatuous,愚笨的,,,,
faultfinder,吹毛求疵的人,,,,
fawn,阿谀奉承,flatter/ adulate,,,
faze ,打扰、使尴尬,absah/ discomfit使窘迫,,fluster 使狼狈,
feckless,无成果的、没有价值的,,粗心不负责任的,,
,bootless/ futile,,sloppy,,
fecund,多产的、肥沃的,,,,
feeble,衰弱的,debilitated/ effete/ enervate,,enfeeble 使衰弱,
fender,缓冲装置、挡泥板,bumper,,,
feral,野生的、凶猛的,动物性的,,,
fervid,酷热的 scorching/ searing/sultry/sweltering,热情的 ardent/ ebullient/ fervent,,,
fervor,热情、狂热,,,,
fester,感染溃烂、腐烂,putrefy 化脓,,,
fetid,恶臭的,effluvial/ malodorous,,ambrosial/ balmy 芳香的,
fetter,枷锁、限制（n）,束缚,,,
fiasco,惨败,debacle,,,
fickle,易变的,不忠诚的,,,
fidelity,忠诚,allegiance,反：perfidy/treachery,,
figurative,比喻的,metaphor 比喻,,,
figurine,小雕塑,,,,
filibuster,掠夺,拖延议事,,,
finesse,娴熟技巧 proficiency,精心策划,（巧妙的）躲避 dodge/eschew/evade,,
finicky,过分讲究、挑剔的,exacting/fastidious/fussy/carp,,,
flaccid,不结实的、松弛的,floppy,,,
flagged,已喝醉的、不能再喝的,,变得衰弱,unflagging 坚持不懈的,
flatter ,拍马屁、奉承,adulate/blandish/court,,自我感觉良好,flattering 令人满足迷恋的
fledgling,新手,veteran 老兵,,,
flinch,畏缩、退缩,,,,
flippancy,轻率、无礼,facetiousness/ frivolousness/levity,,,
flirt,调情 coquet,无规则的快速运动 dart ,,,
flit,快速或突然的经过,plod 缓慢沉重的走,,,
flock,人群、兽群,聚集、集体行动,,,
florid,华丽的、花哨的、绚丽的,,ornate,,
flounder,挣扎、漫无目标、笨拙的行动,,blunder/fumble/lumber/plod,austere 朴素的,
flout,嘲笑、轻视、愚弄,despise,,,
fluky,侥幸的 providential,偶然的 fortuitous,,,
flush,脸红的,富有的,大量的,冲洗,
fluster,使慌乱,abash/ discomfit/disconcert,,,
foible,小缺点,demerit,,,
foil,挫败,baffle/ thwart,,,
foment,助长、煽动,abet/ ferment ,,,
foolproof,万无一失的、肯定成功的,,,,
footloose,无拘无束的、自由的,,,,
forbearance,克制、忍耐,temperance节制、节欲（尤指饮食）,,,
,友好仁慈的态度,clemency,,,
forebear,祖先,antecedent/ ascendant,,,
forestall,预先阻止,avert/deter/preclude ,,,
forge,伪造,锻造、铸就,forger 打铁匠,,
forthright,直率的,不绕弯的,,,
fortify,加固、鼓励,做好心理准备,,,
founder,有‘失败、破坏、跨倒’之意,,,,
fracas,争吵、吵闹,,,,
fracture,破裂,打碎、破坏,,,
frail,虚弱的,effete/enervated/feeble,,意志薄弱的,（希望）渺茫的
fraudulent,欺诈的,duplicitous,guileful,,
fraught,充满的,令人忧虑的,,,
frenzy,疯狂、狂怒,fever/fury/delirium,,frenetic 疯狂的,
fretful,易怒的、烦躁的,fractious/peevish,,,
friable,易碎的,crumbly/feeble/frail,,,
frigid,严寒的 arctic/frosty,冷漠的,,,
fringe,边缘 circumference,接壤abut/ verge ,,,
frivolous,轻浮的  frivolity(n),不重要的,,,
forthy ,用轻薄材料制作的,欢乐轻佻、不严肃的,,,
frowsy,邋遢的 solvenly,味道难闻的 stinky/ fetid ,,,
frugal ,节约的,,,,
挫败、阻挠,baffle/ balk/ foil/ circumvent/ thwart ,,,,
full-bodied,重要的,味道浓烈的,,,
fulminate,大声斥责,denunciate/ reprehend,,,
fumble,笨拙的做,（无意识的）失误,,,
furor,喧闹、激动、狂热,delirium/ frenzy,,,
furtive,鬼祟的、秘密的,clandestine/ surreptitious,,,
`,
//list 11
`
fussy ,谨慎的,过分雕琢的,挑剔的,
fusty,过时的,腐臭的 malodorous/ fetid/ effluvium,,
futile,无效的、无用的,不严肃的 flighty/frivolous/frothy,,
gadfly,刺激物、令人反感的人,,,
gaffe,失礼、失态,明显的过失错误 blunder,,
gainsay,否认,反对,,
gall,激怒,敌意 animosity/animus,大胆、无耻 audacity/brass,
gallant,应用的,高贵的、慷慨的,,
galvanize,刺激,,,
gambol,欢跳、雀跃 ,cavort,,
gangly,身材瘦长的,,,
garble ,曲解、篡改,筛选、除杂,adulterate 掺杂,
gargantuan,巨大的,,,
garish,过于鲜艳张扬的,俗不可耐的,,
garment,衣服 apparel,,,
garrulous,啰嗦的，话多的,loquacious/ voluble,garrulity,
gash,深长的伤口,划伤、戳破,,
gasification,气化,,,
gauche,笨拙的、不善交际的,,,
gaudy,俗艳的 garish,,,
gauge,测量标准,判定,,
gear,调整（以配合）,,,
genial,和蔼可亲的 ,热心友好的 amicable,温暖的,
genteel,有教养的、不粗俗的,,,
germane,有关的、适当的,,,
gibe,嘲弄 deride,,,
giddy,轻浮不严肃的 ,frivolous/ frothy,喜悦的 elated/euphoric,
gild,做多余的修饰,镀上金子的色彩,,
gist,要点,,,
gladiator,角斗士,争论者,,
glaze,给。。上釉、妆点,使平滑,,
glib ,流利圆滑的,肤浅的,,
glisten,闪光,,,
glitch,小故障,,,
gloat,自鸣得意,,,
gloss,简短解释,（欺骗性的）光鲜外表,敷衍了事,开脱罪名
glossy,光滑的、有光泽的,burnished,,
glut,使过量、使充满,,,
glutinous ,胶状的、粘的,,,
glutton,酷爱。。的人,贪吃人 gorger,gluttony 暴饮暴食,
goad,刺激驱使、激发,,,
gobble,狼吞虎咽,devour/ gorge（也有‘峡谷’之意）,nibble 小口咬,
gourmand,大胃王、嗜食者,,,
goggle,凝视,,,
goldbrick,逃避工作和责任,,,
gossamer,虚无缥缈的东西,轻薄的 diaphanous/ethereal,,
gourmet,美食家 connoisseur/epicure,,,
grandeur,高尚、重要,the glory that was Greece and the grandeur that was Rome,,
grandiloquent ,(言语）浮夸的,,,
grandstand,哗众取众、为博取喝彩而卖弄,,看台,
grate,刮擦（发出刺耳声）,骚扰、惹恼 peeve,grating 刺耳的,
gratuitous,无根据的, 不必要的多余的dispensable,免费的、无报酬的,
gregarious,爱社交的 convivial/extroverted/genial,,群居的,
grimace,因痛苦而面部扭曲,,,
grin,咧嘴笑,,,
gripe,抱怨 grumble,惹怒,,
grisly,令人反感恐惧的,appalling/hastily,,
groove,享受、满意、过得快活,,,
grotesque,难看的 hideous ,,,
grovel,卑躬屈膝,,,
grueling,紧张激烈极度疲劳的,,,
guile,狡猾、奸诈,,,
gull,欺骗,gullible 易受骗、易被利用的,,
gush,大量涌出,感情强烈外溢 effuse,,
gust,情感爆发,gush,,
guzzle,狂饮,,,
hack,劈、砍,成功完成,忍受 abide,受雇的文人
hackneyed,陈腐、缺乏创新的,banal/cliché/ hack,,
halcyon,宁静、平静hushed,繁荣丰富的 lush ,,
hale ,强健的 bouncing,拖、拉,,
half-baked,不明智的,,,
hallmark,典型的特征,,,
hallow,尊敬、把。。视为神圣,,,
hallucination, chimera,,,
ham-handed,笨手笨脚的,敏捷的 deft/ adroit,,
hammer ,屡次重申,,,
hamstring,使无效、使无力,,,
hangdog,伤心的、沮丧的,,,
hanker,向往、渴望 craving,,,
haphazard,无秩序的、无目标的 desultory,,,
harangue,长篇大论、滔滔不绝,,,
harass,烦扰,耗尽体力,,
harbor,有‘认为、牢记’之意,,,
hard-bitten,顽强的、经受的住困境的,,,
和谐一致的,eurythmic/ accordant/ concordant,,,
harrow,折磨、使苦恼,agonize/ beset/ excruciate,,
harry,不断烦扰、骚扰,,,
`,
//list 12
`
hasten,促进,,,
hasty,轻率的,,,
hauteur,傲慢、自大,bumptiousness,imperiousness,
haven ,安全的地方,避难所、港口,heaven 天堂,asylum
havoc,大混乱,大范围破坏,,
headlong,鲁莽的,,,
hearken,倾听、关注,harken,,
hearten,给予鼓励、鼓舞,,,
heartrending,令人心碎的,,,
hedonism,享乐主义,,,
hegemony,霸权、统治权,,,
heinous,可憎的、十恶不赦的,,,
hew,遵守hew to tradition,支持,,
herald,告知 annunciate/enunciate/promulgate,,预示、预兆,
heresy,异端邪说、和普遍观点相悖,,,
heretical,异教的、异端的,,,
hermetic,深奥的,arcane/esoteric,,
hidebound,死板的、极度保守的,archconservative,,
hideous,非常丑陋的,,,
hie,快走、催促、赶紧,,,
hike,有‘上涨˙之意,,,
hilarious,非常好笑的,uproarious,,
histrionic,戏剧的、演员的 ,,,
hive,喧闹地区、忙碌之地,蜂箱,,
hoard,贮藏、秘藏,,,
hoary,极老的,灰白的,,
hoax,欺骗,,,
homily,冗长的说教、训诫,bromide/cliché/platitude,,
homogenize,使统一化,,,
hone,磨快,想念,抱怨,
hoodwink,欺骗,,,
hortative,鼓励的,,,
hovel,茅屋 小破脏房,,,
hubris,狂妄自大,bumptious/conceited/imperious,,
humor,有‘迎合、迁就’之意,,,
husband,节俭、勤俭持家,,,
husk,皮、外壳,剥去,,
husky,（声音）沙哑粗糙的,高大威猛的,,
hymn,赞歌、赞美诗eulogy,赞美,,
hyperbole,夸张法（语法）,embellishment/embroidering,,
hypnotic,催眠的 drowsy,,,
hypocritical,虚伪的,,,
iconoclast,特立独行的人,,,
idolatrize,（盲目）崇拜,canonize,,
idyll,无忧无虑的生活,frolic,,
ignominy,耻辱 infamy,,,
illuminati,智者 clerisy,,,
imbibe,喝水、摄入水分,,,
imbroglio,困境、复杂的局面,纷争altercation/squabble,,
immaculate,干净的、纯净的,完美的、无瑕疵的,,
immanent,内在的,,,
immaterial,非实体的ethereal,无关的、不重要的,,
immemorial,古老的 antediluvian,,,
immure,监禁、禁闭,,,
impeccable,无罪的,无瑕的、无可挑剔的,,
impecunious,贫穷的,,,
impending,即将发生的,,,
impenitent,不悔悟的,contrite 悔罪的、后悔的,,
imperial,帝国的、帝王的,巨大的、令人惊叹的epic,,
imperious,爱发号施令的、傲慢专横的,,迫切的,
傲慢的,bumptious/haughty/lofty/peremptory,,,
impertinent,不相干的,粗鲁无礼的,,
imperturbable,沉着淡定的,composed,,
impervious,不可穿/渗透的,无动于衷、不受影响的,,
impetuous,性急的、轻率冲动的,剧烈猛烈的,,
impious,不尊敬的,无信仰的、不虔诚的,反：pious/ reverent,
implacable,固执的,无法平息的、难和解的,,
implode,剧烈收缩、坍塌,,,
imposing,宏伟壮丽的,,,
importune,恳求、迫切请求,conjure/impetrate/implore/petition/plead,,
impostor,冒充者,,,
impotent,无生育能力的 barren,无力的、无能的,,
impromptu,即席表演,即兴的,,
improvise,即兴创作,ad-lib/extemporize,,
imprudent,不明智的,,,
impudent,放肆大胆的、无礼的,audacious/brash/brazen/impertinent/insolent,,
`,
//list 13
`
impugn,责难、抨击,,,
impuissance,无权、虚弱,impotence,impuissant无权无势的,
inalienable,不可剥夺的、不能让与的,,,
inane,空洞的,,,
inaugurate ,使就职,开始,,
incandescent ,明亮灿烂的,热情饱满的,,
incantation,咒语,,,
incarnate,化身的、人体化的,（思想、理论）具化、体现,,
incense,芳香,激怒 exasperate,,
inception,开端、开始,,,
incessant,无间断的,,,
inchoate,新生的,未完全成形的,,
incinerate,烧成灰烬的,incineration 焚化,,
incite,煽动、激起,,,
inclement,（天气）恶劣寒冷的,无情的、严酷的,,
incogitant,考虑不周、不体谅的,,,
incontrovertible,无可争议的,,,
incorrigible,无法管制的,不可救药的、积习难改的,,
控告,impeach,indict,,
incubate,孵化,帮助、培养、促进,,
unculpate,归罪于,,,
indelible,无法擦除的,无法忘怀的,,
indemnity,保险补偿,,,
indifferent,有‘公平的、质量一般的’之意,,,
indigenous,土产的、本地的,与生俱来的、先天的,,
indigent,贫穷的beggared/destitute ,,,
indoctrinate,教育、灌输思想,,,
indolent,懒惰的 shiftless/ slothful/sluggish,,,
inducement,引诱、有权,刺激、鼓励、游说,,induce引诱、导致产生
indurate,铁石心肠的、冷酷无情的,,使变硬congeal,使习惯于inure
ineffable,难以表达的,,,
ineluctable,无法逃避的、必然的,,,
inept,愚笨的、荒谬的,不恰当的,不称职的、无力的,
inert,惰性的,懒惰的,,
inexorable,无法劝阻的、不为所动的,,,
infamous,臭名昭著的,opprobrious,infamy (n),
infatuate,使迷恋,,,
inferno,大火,地狱,,
infiltrate,秘密潜入,abscond逃匿潜逃,,infiltration 潜入、渗透
infirm,虚弱的 debilitated/effete/enervated/feeble/frail,,,不果断的、优柔寡断的
infelicitous,不幸的hapless ,不恰当不合时宜的inept,,
influx,涌入,,,
infuse,灌输、使。。充满,鼓舞,,
infuriate,激怒 umbrage,,,
ingenuity,独创性,ingenuous真挚的 ingenious 聪明的,,
ingrained,本质的、根深蒂固的 immanent/ indigenous/inveterate,,,
ingratiating ,讨人喜欢的,逢迎的、奉承的 ingratiate讨好,,
inimical,带有敌意的,有害的,,
iniquity,邪恶、不公正,,,
inkling,小提示,略知,,
innocuous,无害的,乏味的、不会招致反对的 bland,,
inquisitive,过分好奇的,incurious 无好奇心的,,
insipid,（食品）清淡无味的,平淡无聊的 driveling/prosaic/tedious/vapid,,
insolent,粗野的、无礼的,傲慢的、无耻的haughty/supercilious/impudent,,
insouciant,无忧虑的、不在乎的nonchalant,,,
Instate,任命,designate/inaugurate/induct,,
instigate,煽动、激起,abet/foment/goad,,
instill,慢慢滴入,灌输,,
insubordinate, 不服从权威的 balky/contumacious,,,
insulate,使绝缘、使隔离,,,
insurgent,叛乱分子,anarchist/antagonist,,
intelligible,可理解的 fathomable/lucid,,,
intemperate,无节制的、极端的、不温和的,,,
inter,埋葬 entomb/inhume,,反：disinter/exhume,
intercessor,调停者,intercession 调停,,
interdict,禁止,阻止,,
`,
//list 14
`
interminable,无尽头的,,,,
intermittent,间歇的、断断续续的,,不定期的,,
interregnum,过渡期,,,,
interrogate,质问、审问,,,,
intimidate,威吓 coerce/hector,,,,
花言巧语讨好,blandish/cajole/coax,,,,
intrepid,无畏的,,,,
怯懦胆小的,cowardly/craven/gutless/pusillanimous/trimorous,,,,
intrigue,阴谋,激起。。的兴趣,,,
inundate,淹没,,,,
inure,使习惯、适应,有助于,使坚强,,
invective,侮辱性的,,,,
inveigh,强烈抗议、表示不满,,,,
inveigle,诱骗 balt/decoy,,,,
inveterate,有恶习、成瘾的,根深蒂固 的,,,
invidious,惹人反感的,羡慕嫉妒恨的,,,
invincible,不可战胜的、不可超越的,,,,
irascible,易怒的,choleric/peevish/petulant,,,
iridescent,五颜六色的,,,,
irk,使烦恼,令人烦恼的事物,,,
ironclad,坚不可摧的,,,,
irradicable,不能根除的、根深蒂固的 entrenched/ingrained,,,,反：eradicable
jabber,快而不清楚的说 babble/blabber/drivel/gabble/jabber,,,,
jaded,疲惫的,厌倦的、无热情的,,,
jape,嘲弄,,,,
jarring,刺耳的,震惊的,,,
jaundice,偏见,乖僻,,,
厌恶、仇恨,animosity/ animus/ antagonism/ antipathy/ gall,,,,
jaunty,轻快活泼的,,,,
jejune,无趣乏味的 tedious ,,幼稚的,,
jest,轻浮的态度,戏谑,,,
jeopardy,危险,,,,
jettison,抛弃、丢弃 dump/scrap,,,,
jibe,意见一致,,,,
jingoist,极端爱国激进分子,,,,
jitters,紧张、不安 dither/jimjams,,,,
jocular,搞笑的、欢乐的 lithesome/gleeful/jocund/mirthful,,,,
jocund,欢乐的,,,,
jolt,突然移动,惊吓,,,
jot,简要记录,jot down,,,
jovial ,愉快的,,,,
jubilant,喜悦的,,,,
juggernaut,巨大的力量,重型卡车,,,
ken,视野范围,知道、了解,,,
kindred,类似的 congenial,同类的、血缘的,,,
knack,诀窍 artifice,聪明的做法,,,
knead,揉捏、塑造,,,,
kudos,名望、名声,反：infamy/notoriety,,夸奖,
labile,易变的、不稳定的,,,,
labyrinthine,迷宫似的、复杂曲折的,,,,
lacerate,使非常痛苦 afflict/distress/harrow/rend/torment,,,,
lackluster,黯淡无光泽的 dim/lusterless,,反：burnished/lustrous,,
laconic,简洁 apothegmatic/succinct,,,,
lachrymose,催人泪下的、悲伤的,,doleful/lugubrious/melancholy,,
lampoon,讽刺,,,,
languid,虚弱的、无精打采的,languish 变得虚弱,,,
languor,懒惰、衰弱,,,,
lank,细长瘦弱的emaciated,柔软松弛的droopy/floppy,,,
lapse,小过失blunder/fumble,结束、终止,,,
largesse,捐赠物,慷慨,,,
lash ,击打,猛击撞击,捆扎,,
lassitude,乏力、没精打采,,,,
latitude,（行为or言论）自由,,,,
laudatory,表示赞扬的,extolling/eulogistic,,,
leaven,渐变,潜移默化的影响,,,
leer,一瞥、斜眼看,,,,
leery,怀疑的、不信任,credulous 轻信的,,,
legion,大量的人、军团,大量的,,,
lenient,宽大仁慈的 clement,,,,
lethal,致命的 baleful/pestilent,,,,
lethargic,没精打采的、行动迟缓的,,,,
levelheaded,明智的,,,,
levity,轻浮 facetiousness/flightiness/flippancy/frivolousness,,,,
`,
//list 15
`
liberal,有‘慷慨大方的‘之意,,
libertine,放荡不羁者、花花公子,,profligate
licentious,放荡的、性欲强的,,frigid 寒冷的、性冷淡的
limber,可塑的、柔软的 lissome/lithesome/pliable,,
limp,柔软松散的,软弱没精神的,跛行
limpid,透明清澈的,镇定淡定的,
lissome,柔软的,敏捷轻盈的,
list,有‘倾斜’之意,,
lithe,敏捷轻盈的,柔软的,
loll,懒洋洋的行动,偷懒、打发时间,
lopsided,歪的,不协调不平衡的,
loutish,粗鲁的,boorish/churlish,
lubricate,使润滑,lubricant 润滑剂,
lucid,有光亮的,神志清醒的,表达清晰易懂的
lug,拖动,费力搬运,
lugubrious,悲哀的、阴郁的 deploring/doleful/dolorous/melancholy,,
lull,平静时期、间隙,使镇静、安心,
lumber,木材 timber,笨拙的行动,使负担
luminary,杰出人物 eminence/notability,,
lurch,蹒跚dodder/falter/stagger/totter/waddle,,
lurk,潜伏,,
lush,茂盛的exuberant,多产的,优美的、令人愉悦的
lustrous,有光泽的,,
macabre,恐怖的 ghastly,atrocious 残忍恶毒骇人听闻的,
macerate,浸泡（以软化）,,
maculate,使有斑点、弄脏 besmirch,,
maelstrom,漩涡 vortex/whirlpool,混乱动荡的局势,
maladroit,笨拙的,,
malaise,不舒服,,
malicious,恶意的 malevolent/malign,,
malign,恶意的,诽谤asperse/calumniate/libel,
malinger,装病以逃避工作,,
malleable,可塑的 ductile,以控制的,
malodorous,恶臭的 fetid/frowsy/funky,,
mangle,损毁、使伤残,弄砸bumble/fumble,
mangy,卑劣的,,
mania,热衷、狂热,,
manumit,解放（奴隶）,,
mar,污点、坏点 blotch,破坏、削弱blemish,
marsh,沼泽、湿地,,
martinet,纪律严明之人,,
masquerade,面具guise,伪装、掩饰disguise,
matriculate,入学、录取,,
maudlin,过于感伤的,,
maven,专家  connoisseur/virtuoso,,
maverick,特立独行的人,不合常规的,
meager,贫乏的,,
meander,闲逛、漫步 stroll,,
measly,微不足道的,患寻麻疹的,
meddle,干涉、管闲事,meddlesome 爱管闲事的,
mediate,调解调停 conciliate,,
medly,大杂烩、混杂物 agglomeration/hodgepodge,,
meek,谦恭的,顺从的 docile/tractable,
mellifluous,（曲调）优美的,dulcet/melodious,反：cacophonous/raspy
melodramatic,感情夸张的、伤感的,,
menace,威胁、使处于危险,imperil/jeopardize,
mercenary,雇佣军,唯利是图贪婪的acquisitive/avaricious/avid,
mercurial,情绪）善变的,,
merited,应得的、理所当然的 condign,,
mesh,诱捕 entoil,,
mesmeric,催眠的 hynoptic,令人着迷难以抗拒的 riveting,
metamorphose, 变形   alchemize使变质、使变形,,
metaphysical,哲学上的、理论上的,非尘世的 ethereal,
meteoric,流星般迅速短暂的,,
methodical,井然有序的、有条理的,,
meticulous,极为谨慎的  punctilious,,
mettle,勇气,毅力、耐力 fortitude/stamina,
miff,使恼怒,,
mime,模仿,ape,
minatory,带来威胁的、有凶兆的,,
mince,切碎 hash,小步走    大步走stride,
`,
//list 16
`
mingle ,参加社交活动; 混合,,
mint, 巨额；无损坏的,,
minutia  ,次要的细节；小事,,
mirage ,海市蜃楼，幻想,,
mire ,困境；使陷入困境,,
mirth ,欢乐、欢笑,,
misanthropic,反人类的,,
mischievous,调皮的,有害的,
miscreant,恶棍、罪犯,,
misgiving,担忧、疑虑,,
mishap,不幸之事,,
misrepresent,误传、篡改,,
mite,微小的东西,很少的钱,
mitigate,减轻缓和痛苦,,
molt,脱（皮、羽毛等）,,
mongrel,杂种的、混血的,,
monochromatic,单色的,单调无聊的,
monologue,独白,,
montage,大杂烩,aggolomerate,
moratorium,延期、暂缓施行,,
morbid,病态的,思想变态的,
mordant,尖酸刻薄的,,
moribund,即将结束的、垂死的,,即将过时的
morose,忧郁的,lugubrious,dire
mosaic,综合物，马赛克般的东西,,
mosque,清真寺,,
moth-eaten,过时的,,
motile,能动的,,
motley,混杂的，富于变化的,,
mottle,斑点、杂色,使呈杂色,
muffle,使消声,,
mulish,固执的,,
mumble,说话含糊,,
mundane,世俗化的,平凡的,
munificent,慷慨的,,
murky,暗淡昏暗的,模糊晦涩的,
mutter,低声抱怨,,
myopic,缺乏远见】缺乏辨别能力,,
myriad,无限的、大量的,,
nadir,最低点,,
narcissism,自恋,,
nascent,新生的,,
natty,整洁时髦的,,
nauseate,厌恶、作呕,,
nautical,航海的,,
naysay,拒绝、否认,gainsay,
nebulous,模糊的,,
nefarious,极坏的、邪恶的,,
negation,否定,,
negligent,疏忽大意的,,
neophyte,初学者、新手,,
nerve,意志、勇气,,
nettle,惹怒,,
neutralize,中和,破坏、使无效,
nicety,准确、精确,细微之处,
nexus,连结,核心、最重要的地带,
nil,不存在、零,,
nip,少量,小口吃喝,
nitpick,吹毛求疵,,
nocturnal,夜间的,nocturne 夜曲,
noisome,有害有毒的,恶臭的,令人厌恶的
nomad,游牧的、居无定所的人,,
nonchalant,冷漠的,,
nondescript,平凡的、不吸引人的,,
nonentity,不重要的人,虚构的东西,
nonplus,迷惑、困惑,,
notch,刻痕,通过努力获得,
`,
//list 17
`
nudge,用肘轻推,唠叨,说服某人做某事,
nugatory ,无关紧要的,,,
obdurate,固执的,冷酷无情的,,
obliging,乐于助人的,,,
oblique,斜的,,,
obliterate,除去,,,
oblivious,不知情的,,,
obloquy,谩骂、诽谤,恶名、耻辱,,
obsequious,谄媚的、奴性的,,,
obstinate,固执的,难以减轻或治愈的,,
obstreperous,难驾驭的、任性的,,吵闹的,
obtuse,愚钝的,,,
obviate,排除、使不必要,,,
occult,难以理解的,使隐藏或神秘,,
odium,憎恶、讨厌,,,
offbeat,不平常的,,,
offhand,即兴的、没有准备的,,,
officious,多管闲事的,,,
offish,冷淡的,,,
off-key,不寻常的、不合适的,,,
ominous,凶兆的,,,
omniscient,无所不知的,,,
onerous,费时间花心思的,,,
opine,表达观点,,,
opportune,合适的、适当的,,,
opprobrious,辱骂的,臭名昭著令人鄙视的,,
oration,演说,harangue 长篇大论,,
oscillate,振动、摇晃,犹豫、变化,,
ossify,硬化、僵化,,,
ostentatious,炫耀卖弄的,,,
ostracize,驱逐,,,
oust,免职,驱逐,,
outmaneuver,以策略取胜,,,
outset,开端、开始,,,
outwit,瞒骗,以智取胜,,
overt,明显的、公开的,,,
overture,前言、序曲,,,
oxymoron,矛盾修饰法,,,
pacify,使平静、安慰,conciliate/propitiate,,
padding,夸张、废话,,,
paean,欢乐颂,,,
palatial,宫殿般奢华的,,,
pall,失去兴趣,,,
palliate,平息、减轻,,,
pallid,无生气的、缺乏活力的,,苍白无血色的,
palmy,繁荣的,,,
palpable,摸得到的,明显的、易察觉的,,
palter,欺骗,,,
paltry,无价值的、微不足道的,让人厌恶鄙视的,,
pan,严厉批评,,,
panache,炫耀,,,
pandemic ,大范围流行的,,,
pandemonium,喧嚣、骚动,,,
panoramic,全景的,panorama,,
parable,寓言,,,
paragon,优秀模范,比。。比作,,
paramount,最重要的,,,
paranoid,多疑的,credulous 轻信的,,paranoia 偏执狂
paraphrase,转述、意译、改写,,,
parch,烤干,,,
pariah,被排斥的人,社会遗弃者,,
parody,拙劣的模仿,滑稽模仿,,
paroxysm,突发,大动荡,,
parrot,（机械的）模仿、复制,,,
parry,躲避（问题）,,,
particularize,详述,,,
partisan,跟随者、信徒,拥护者,偏袒的,
pastiche,（带嘲讽的）模仿burlesque,,大杂烩,
pathological,不正常的、病态的,,,
patina,外表,氛围、气场,,
`,
//list 18
`
patrician,贵族,,,
patronize,赞助,与高人一等的态度对待,,patron 赞助人
paunchy,大腹便便的,,,
peck,大量,啄食,,
pedagogue,教育者、老师,,,
pedant,书呆子,墨守成规的人,,
predestined,预先注定的,predestination 命中注定,,
peep,一瞥,轻声,,
peeve,打扰、惹恼,peevish 易怒的、脾气不好的,,
pejorative,轻蔑的、贬低的,,,
pellucid,透明的,清晰易懂的,,
pen,监狱,关押、监禁,,
penchant,强烈嗜好、迷恋,,,
penitent,悔过的 contrite,,,
penury,贫穷,吝啬,,
perambulate,徒步穿越、走过,,,
peremptory,不容反抗的,爱发号施令的,傲慢的,
perfervid,非常热情的,,,
perfidy,不忠、背信弃义,,,
perforate,打孔、穿透,,,
perfunctory,敷衍的,肤浅的,,
perimeter,边界、界限,,,
peripatetic,巡游的,,,
peripheral,外围的,辅助性的,,
permeable,可渗透的,,,
peroration,（演讲）结束语,演讲、致辞,,
persevere,坚持不懈、不屈不挠,,,
persecute,迫害、折磨,,,
persiflage,打趣,,,
personable,英俊的,,,
perspicacious,敏锐有洞察力的,,,
perspicuity,清晰明了的,,,
pertain,有关联,,,
pertinacious,顽固的,,,
pertinent,相关的、恰当的,,,
perturb,扰乱、使烦躁,,,
peruse,细读,,,
pervade,弥漫、充满,pervasive 弥漫的,,
petrify,使僵化、失去活力,,,
petty,细微的、不重要的,,,
philanthropic,博爱的、为他人着想的,,,
philistine,市侩、庸人,,,
phlegmatic,冷静的、无感情的,,,
piddling,微不足道的,,,
piebald,混合杂糅的,杂色的,,
pilfer,偷窃,,,
pillory,被示众嘲弄,,,
pine,渴望、奢望,因渴望而憔悴,,
pinnacle,顶峰,,,
pinpoint,非常精确的,精确定位,,
piquant,辛辣开胃的,令人振奋的
pique,使愤怒,激起、刺激,,
pirate,盗版、盗用,海盗,,
piyhy,简洁精炼的,,,
pitiless,没有同情心的,,,
pittance,少量津贴,,,
placate,平息抚慰,,,
placebo,安慰性的事物,,,
plangent,轰鸣的,凄凉哀伤的,,
platitude,陈词滥调,,,
pleat,打褶,褶,,
plentitude,大量,myriad,,
plethora,过量、过剩,,,
pliable,易弯曲的,易受影响的、柔顺的,,
pilant,易弯曲的,limber,顺从的,
pluck,勇气,弹奏（弦乐）,,
plumb,测深度 fathom ,垂直的,完全绝对的,仔细深入调查
plummet,突然下降,,,
plump,丰满的,赞不绝口,,
plunge,突然下降,插入、刺入,,
polemic,争执,,,
politic,精明的,合时宜的,,
pompous,浮夸的,傲慢的,,
`,
//list 19
`
ponderous,沉重的,沉闷无聊的,
pontificate,傲慢的说或做,,
pore,仔细浏览研究,,
porous,多孔可渗透的,permeable,porosity 多孔性
portentous,预兆性的、凶兆的,勾起兴趣的、令人遐想的,
poseur,故作姿态、不真诚的人,,
posit,假定、断定,,
postulate,前提条件,假定为真,
potable,酒精饮料,适于饮用的,
potentate,有权的人,君主、统治者,
potentiate,激活、加强,,
pout,撅嘴,生气,
practitioner,职业人士,,
prairie,大草原,,
prate,闲聊、空谈,,
preach,传教布道,,
precarious,危险不稳定的,可疑不明确的,
precipice,悬崖峭壁,,
precipitate,匆忙的 precipitous,促进、导致,
precipitous,险峻陡峭的,,
preclude,预先阻止,排斥,
precursor,先驱者、先导,,
preeminent,优秀的、重要的,,
preempt,预先占有,替换,preemptive先发制人的
preen,整理（羽毛）,打扮修饰,自满
pregnant,有‘重要的、意味深长的’之意,,
preoccupation,非常关心,全神贯注,
preponderant ,占优势的,更重要的,
prepossessing,给人好感的,,
preposterous,荒谬的、不合常理的,,
presage,征兆,预言,
prescription,规定、传统的规矩,prescribe 开药方、立规矩,
presumptuous,放肆的、冒昧的,傲慢的,
pretense,虚假、伪装,自大、优越感,
prevaricate,支吾其词、撒谎,palter,
primordial,原始的、最初的,,
primp,精心打扮,,
pristine,纯净质朴的、未被文明腐蚀的,,
privation,缺乏、穷困,,
probity,正直,,
procure,获得、取得,,
prod,促使。。行动,,
prodigal,挥霍的,败家子,profligate也有‘挥霍的、浪子’之意
prodigious,巨大的,惊人的、了不起的,
profane,亵渎,滥用,
proffer,献出、提供,,
profligate,挥霍的 prodigal,败家子、堕落的人,
profusion,丰富、大量,挥霍、浪费,
prolix,啰嗦冗长的,,
profread,校对,,
promulgate,正式宣布,,
propensity,倾向、癖好,,
prophetic,预言的、预示的,,
propitious,吉祥的 auspicious,portentous 凶兆的,
proponent,建议者、支持者,,
propriety,礼节、适当得体,decorum,
prosaic,单调的、无聊平淡乏味的, ,
proscribe,禁止、排斥,,
prosecution,实行、执行,,
proselytize,改变信仰,,
prospect,探查、勘测,期待,
prostrate,平躺,衰弱的/使枯竭,
protean,善变的、多才多艺的,,
protocol,礼仪、外交礼仪,协议、规范,
protract,延长、拖长,,
protrude,突出 bulge,,
protuberant,隆起的、凸出的,,
provident,节俭的、有远见的,,
providential,大量的、幸运的,,
provisions ,临时的,,
provisory,有附带条件的、临时的,,
`,
//list 20
`
prowess,英勇、勇敢,gallantry,,
prowl,潜行、徘徊、搜索,,,
prude,拘守礼仪、故作正经的人,,,
prudish,过分守礼的,,,
pucker,撅（嘴）折叠、使收缩,,,
puckish,淘气、顽皮的,,,
puerile,幼稚不成熟的,,,
puissance,权力,,,
pulchritude,美丽,,,
pulverize,研磨成粉,,,
pun,双关语,,,
punctilious,注意细节的、一丝不苟的,,,
pundit,权威人士、专家,,,
pungent,辛辣的、讽刺的,,,
puny,微小的、弱小的,,,
purlieu,范围、界限,常去的地方,,
purloin,偷窃,filch/plifer,,
purvey,（大量）供给、供应,,,
pusillanimous,懦弱胆怯的,craven,,
quack,骗子医生、江湖郎中,,,
quaff,大口吃喝,,,
quail,胆怯、畏缩,,,
quandary,窘境、左右为难,,,
quarantine,隔离,,,
quarry,采石厂,目标、猎物,,
quash,镇压、阻止,,,
quaver,发颤音,,,
quell,压制,使平静、安静,,
quench,熄灭,使满足,,
querulous,抱怨的、,爱发牢骚的,,
quibble,诡辩、挑剔,谬论、双关语,,
quiescent,平静的、静止的,,,
quixotic,不切实际的、空想的,,,
quotidian,平凡的,每日的,,
rabble,混乱的人群,,,
rabid,狂热的,不冷静的,,
racy,活泼生动的,,,
raffish,低俗的,,,
raffle,垃圾、废物,,,
ragged ,衣衫褴褛的,凹凸不平的、不光滑的,,
rail,怒骂、猛烈抨击,,,
rakish,放荡的、行为不检点的,,,
rambunctious,喧闹的、骚乱的,,,
ramshackle,摇摇欲坠的,,,
rankle,激怒,,,
rant,(长时间）训斥、责骂,,怒吼,
rapacious,食量大的、贪食的,,过度贪婪的,
rapport,和睦、友好,,,
rapprochement,和睦、友好,rapport,,
rapscallion,流氓、恶棍,,,
rapt,狂喜的,全神贯注的,,
raspy,声音刺耳的,容易生气的,,
ratify,认可、批准,,,
ratiocination,推理,,,
rave,狂热赞扬,咆哮怒吼,,
ravel,解开、松开,阐明,使纠缠、使复杂化,
ravish,使陶醉、使沉迷,,,
raze ,摧毁、粉碎,,,
reactionary,反对变革的,极保守的,brassbound/hidebound,
ream,怒斥、训斥,,,
reap,收割收获,,,
reassure,使安心、打消疑虑,,,
recalcitrant,顽抗的、不顺从的,,,
recant,撤回、放弃、改变,,recantation改变论调,
recessive,隐性基因的,内向的、内敛的 bashful,,
recidivate,复返、再犯（罪）,,,
reciprocate,往复运动,报答、回报,,
recluse,隐士 hermit,隐居的、不爱社交的,,reclusive 隐居的
recoil,退却、畏缩,,,
recondite,深奥的、难解的 abstruse/arcane/esoteric/hermetic/occult,,,
reconnoiter,侦查、勘查,reconnaissance 名词,,
reconvene,重新集合、重新召集,,,
rectitude,正直,,,
recumbent,躺着的,斜靠的,,
recuperate,恢复、康复,,,
redolent,芳香的,,,
redoubtable,杰出的、值得尊敬的,,可怕的direful,
reel,感到眩晕,蹒跚的走路falter/totter,,
`,
//list 21
`
referee,仲裁者,给出意见,,,
refractory,倔强的、不顺从的,,,,
refulgent,辉煌灿烂的,,,,
regimen,(政治)统治,,,,
rehabilitate,使康复/复原,rehabilitation 康复、复原,,,
rein,抑制、限制,,,,
relapse,旧病复发、故态复萌,,,,
relentless,残酷无情的,固执不妥协的,,,
relinquish,放弃(职位、权力)、 移交、交出,,,,
relish,喜好、偏好,享受、喜欢,（愿望达成）满足,,
remiss,疏忽的、不留心的,,,,
remonstrance,抗议、抱怨,demur,,,
remorse,懊悔、悔恨,,,,
remunerate,支付报酬或补偿,,,,
rend,撕裂、猛拉,lacerate,,,
renegade,背教者、叛徒,,,,
renounce,宣布放弃 abnegate,宣布与。。决裂,,,
renovate,修复、维修,使重获新生,,,
repartee,机智的回答,打趣、善意玩笑persiflage/badinage,,,
repatriate,遣返,,,,
repeal,撤销、废除,放弃,,,
repel,击退、抵制,使不愉快,,,
repertoire,全部节目、详单,,,,
repine,抱怨、表达不满,渴望,,,
repose,休息、睡眠、静止,寄托于,,,
reprehend,谴责、批评,reproof/reprove,,,
reprieve,暂缓处刑、免罪,维持运行,,,
reproach,耻辱,责备admonish/berate/castigate/chide/rebuke/reprove,,,
reprobate,堕落者、道德败坏的人,拒绝,,,
reproof,批评、反对,,,,
reprove,温和的责备、警告,不欣赏、不喜欢,,,
repudiate,否认,拒绝接受,,,
repugnant,令人厌恶的,矛盾的,,,
requite,酬谢、报答,报复,,,
requisite,必需品、必不可少的,,,,
rescind,废除、取消,,,,
resourceful,有创造力的、机智的,,,,
respite,间歇、休息,lull,,,
respire,呼吸,,,,
resplendent,华丽辉煌的,refulgent,,,
restive,急躁忧虑的,难以管束的,倔强不安宁的,,
resuscitate,使复活、使苏醒,,,,
retainer,家仆,定金,,,
retaliate,报复、反击,remunerate 支付报酬或补偿,,,requite 报酬报答、报复
retard,减速、延迟,,,,
retinue,随行人员,,,,
reticent,沉默不语的,不愿意的,,,
retort,(机智的)回应,repartee,,,
retouch,润饰、改进,,,,
retract,收回、否认,,,,
retribution,报偿、报应,,,,
retrograde,倒退的,退步、退化,,,
revelry,狂欢、喧闹作乐,,,,
revere,(对神的)尊敬,,,,
ribald,举止、言语下流的,,,,
rickety,不稳的 precarious,,,,
rife,丰富的、普遍的,,,,
rift,离间,使开裂,,,
rile,刺激、惹怒,,,,
riot,喧闹、暴乱,,,,
rite,惯例、仪式,,,,
rive,撕开,,,,
`,
//list 22
`
riveting,吸引人的、迷人的,,
rivulet,小河、小溪,brook,
roil,搅浑、使混乱,激怒,
roisterer,喝酒喧闹的人,,
roster,值勤表、花名册,,
rostrum,讲坛、演讲坛,,
royalty,有‘版税’之意,,
rubicund,红润的,健康的,
rudimentary,初始的、未发展的,最根本的、基础的,
rue,后悔、遗憾,remorse/contriteness/contrition/penitence,
ruffle,皱褶花边、使粗糙,打扰扰乱,rumple
ruminate,沉思 cogitate,,
rumple ,弄皱,打乱、使不整齐,ruffle
runic,神秘的,,
rupture,打碎、打破,,
ruse,诡计,,
rustic,乡下人、头脑简单的人,乡村的 bucolic,粗俗的
rustle,快速的行动,,
sabotage,妨碍、破坏,从事破坏活动、阻止,
saccharine,有甜味的,做作、甜的发腻的,
sacrilege,亵渎圣物,,
saddle,使某人负担,,
sage,智者,,
salubrious,有益健康的. Salutary,,
salutation,致敬、打招呼,表扬,
salvage,(从灾难中)抢救,,
salve,减轻、缓解,,
sanctify,使神圣、敬为神,,
sanctimonious,假装虔诚的,,
sanctuary,避难所 asylum ,,
sand,用砂纸磨光,,
sanguine,面色红润的 rubicund,乐观的、确信的,
sanitary,健康的、清洁的,,
sap,削弱（v),健康、活力,
sapient ,聪明的、有洞察力的,,
sarcasm,讽刺、轻蔑,,
sartorial,裁缝的,服装的,
sate,使饱足、充分满足,,
satiate,饱足、过分满足,,
saturnine,忧郁阴沉的,讥讽的,
saunter,闲逛、漫步,,
savant,博学之士、智者,pundit,
savory,口感、味道好的,令人愉悦的,
savvy,悟性、理解,老练机智,有见识精明的
scads,许多、大量,,
scant,不足的、缺乏的,,
scathing,尖酸刻薄的 acerbic/pungent,,
schism,不一致,,
scintillate,闪耀 gleam/glimmer/glisten/luster,,
scion,子孙,,
scission,切断、分离分裂,,
scoff,嘲笑、狼吞虎咽,,
scorn,轻蔑、不屑,,
scotch,停止,,
scour,用力擦洗,搜查,
scowl,皱眉、怒视,,
scrappy,好斗的、好吵架的,,
scrap,废物、废料,抛弃,终止、放弃原计划
scribble,潦草的写、乱写,scrawl/scratch,
scrupulous,正直的,一丝不苟的,
scrutable,可以理解的,,
scuff,磨损,脚步拖沓,
scurrilous,说粗话的,invective,
scurvy,下流粗鄙的,ribald,
seamy,肮脏堕落的,,
secluded,隐僻的 ,cloistered 隐居的、躲开尘世纷争的,
sedate,淡定的、安静的,,
sedentary,不爱活动的、坐着的 ,a sedentary lifestyle 宅,
seduce,诱使做坏事,decoy/entice/solicit,
sedulous,勤奋认真的,,
seemly,得体的、遵守礼节的,,
self-abasement,自卑、自谦,,
self-absorbed ,自恋的、自私的,,
seminal,有发展性的,创新的,
sentinel,哨兵、看守,,
sepulchral,阴沉的,丧葬的、坟墓的,
septic,腐败的、感染的,,
sequela,结果,precursor 先兆,
sequester,使隔绝、分离,使隐退,
sere,干枯的、凋萎的,,
serendipity,意外发现珍奇事物的才能/运气,,
`,
//list 23
`
sermon,布道、说教,preach/homily,
serpentine,弯曲的,,
serrate,锯齿状的,notch 刻痕,
serried,密集的,,
servile,低下的、卑屈的,,base
shackle,束缚,限制、阻碍,
sham,欺骗；虚假的；掩饰假装,,
shiftless,无志气的；懒惰的,,
shipshape,井然有序的,,
shirk,逃避,,
shoal,浅的,,
shopworn,陈旧的,,
shred,少量,,
shrewd,精明的；强烈的,,
shrug,耸肩；轻视忽略；脱下,,
shun,避开,,
shrink,减少；退缩；犹豫,,
shroud,隐蔽物；遮蔽,,
sidestep,不遵守,,
signal,非同寻常的；发出信号,,
simpleton,笨蛋,,
simulate,模仿；模拟,,
sin,罪恶的事,,
sincere,真诚的,,
sinecure,美差,,
sinew,活力，力量,,
singe,轻微烧焦,,
sinuous,蜿蜒曲折的,,
sip,啜饮,,
skeleton,骨架,,
skeptic,怀疑者,,
skimp,吝啬；节省花费；缺乏的不足的,,
skirmish,小冲突,,
skirt,回避；边界,,
slack,松弛的；疏忽大意的,,
slake,使满足,,
slant,角度看法；倾斜的；歪曲,,
slate,列入名单计划,,
slew,大量,,
slight,纤细的；少量的；轻蔑；疏忽,,
sling,投掷,,
slippery,光滑的；隐秘的；意义不明确的,,
slipshod,粗心的,,
sloppy,邋遢不整洁的；混乱的,,
sloth,懒惰,,
slouch,懒人；缓慢行走,,
slovenly,邋遢的,,
sluggard,懒鬼,,
sluggish,迟钝的；缓慢的,,
slumber,睡着,,
slur,含糊地发音；忽略；耻辱,,
sly,狡猾的；隐秘的,,
smarmy,虚情假意的,,
smart,反应敏捷的；整洁的；感到疼痛,,
smattering,浅薄的知识；少量,,
smirk,自鸣得意地笑,,
smother,使窒息；压抑,,
smug,自大的；整洁的,,
smuggle,走私,,
snare,捕捉；无法逃脱的困境,,
snarl,纠缠；咆哮,,
sneer,轻蔑地嘲笑,,
snobbish,自大的,,
snub,轻视,,
soak,浸泡,,
sober,严肃的；节制的；有理有据的,,
sodden,浑身湿透的；使湿透,,
solace,安慰安抚,,
solder,连接联合,,
solemnity,严肃,,
solicitous,关心挂念的；迫切渴望的,,
solidify,凝固,,
soliloquy,独白,,
solitude,孤独,,
solvent,有偿付能力的；溶剂,,
somatic,肉体的,,
somber,忧郁的；昏暗的,,
somnolence,瞌睡,,
sonnet,十四行诗,,
soothe,安慰；使安心；缓解,,
sop,安慰物；贿赂；浸湿,,
sophism,诡辩,,
sophistication,精明,,
soporific,安眠药；催眠的；困倦的,,
sordid,肮脏的；卑鄙的,,
sound,稳固的；健康强壮的；逻辑严谨的,,
sparse,稀疏的,,
spartan,简朴的，节约的,,
spat,小争吵,,
spate,突发的洪水；大量,,
specific,特有的；明确的,,
specious,似是而非的，欺骗性的,,
speck,少量,,
spectator,观众,,
spectrum,光谱；范围，系列,,
speculate,推测；投机倒卖,,
spendthrift,败家子；挥霍的,,
`,
//lsit 24
`
spindly,细长纤弱的,
spiny,多刺的；棘手的麻烦的,
spleen,怒气,
splice,接合,
spoof,小恶搞；诱骗,
sporadic,偶尔的；零星发生的,
sprawl,蔓延；杂乱无序地发展,
sprightly,活泼的，充满活力的,
spurious,伪造的,
spurn,拒绝,
squabble,小争吵,tiff
squalid,污秽的；道德败坏的,
squall,暴风雪暴风雨；尖叫,
squander,浪费；使分散,
squat,又矮又胖的,
squint,斜视,
squelch,压制；击溃,
stamina,耐力,
stammer,口吃,
startle,使大吃一惊,
stature,身高；才干水平,
steadfast,坚定的；忠诚的,
stealth,秘密行动；秘密的,
stench,恶臭,
stentorian,声音洪亮的,resonant
stifle,抑制；扼杀,
stint,吝惜,
stingy,吝啬的；极少量的,
stipple,点刻；用点标记,
stipulate,特定要求，规定,
stitch,突然剧痛,
stockade,围栏；监狱,
stodgy,平庸的；非常守旧的,
stoke,添加燃料；促进,
stoic,冷静的 隐忍的,
stolid,无动于衷的,
stomach,容忍,
stonewall,拒绝合作，阻挠,
stouthearted,大胆的、勇敢的,
stratagem,谋略,
strait,海峡；痛苦,
stray,离群；迷途；漫无目的的,
striate,加条纹、条纹的,
stricture,责难,
stride,迈大步走,
strident,刺耳的,
strut,趾高气扬地走；支柱,
stultify,使无效,
stupor,迟钝；无知觉,
stunt,阻碍成长,
sturdy,强健的,
stygian,极阴暗的,
stymie,阻碍,
subdue,征服；压制；减轻,
subjugate,征服镇压；剥夺自由,
sublime,崇高的；令人惊叹的,
subliminal,下意识的,
submerge,使淹没,
subservient,奉承的；屈从的,
subside,下沉；减弱,
substantiate,证实；使实体化,
substantive,本质的,
subterfuge,托辞；诡计ruse,
subvert,颠覆,
succor,救援,帮助
suffocate,使窒息,
sulk,生气恼怒,
sullen,闷闷不乐的,
summon,召集；传唤出庭,
sumptuous,豪华的,
`,
//list 25
`
sunder,分裂,,
supercilious,高傲的,,
superfluous,多余的,,
superimpose,添加,,
supine,懒散的；消极倦怠的,,
supplant,排挤；篡夺位置,,
supple,易弯曲的，柔软的,,
supplicate,恳求,,
surcharge,过高收费,,
surfeit,过量；饮食过量,,
surreptitious,偷偷摸摸的,,
suture,缝合,,
svelte,苗条的优雅的,,
swagger,大摇大摆地走；自夸,,
sweltering,酷热的,torrid,
swerve,突然改变方向,,
swill,痛饮，大口地吃,guzzle,
swindle,欺骗,,
sybarite,奢侈淫乐者,,
sycophant,马屁精,toady,
syllabus,课程大纲；摘要,,
syllogism,推理演绎,,
symbiosis,共生关系,,
synchronous,同时期的,,
tacit,暗示,,
taciturn,沉默寡言的,,
tactile,有触觉的,,
tactless,不机智的,,
talisman,护身符,,
tamper,窜改；损害,,
tangent,离题的；不相关的,,
tangy,刺激的,,
tantalize,逗弄、引诱、折磨,,
tantamount,等价的；与…相等的,,
tantrum,勃然大怒,,
taper,逐渐变细；减弱；烛芯,,
tardy,缓慢的；延后的,,
tarnish,玷污,,
tatty,破旧的；褴褛的,,
taunt,嘲弄、讥讽,,
taut,紧绷的；整洁的,,
tawdry,俗丽的,,
taxing,繁重的；费力的,,
teeter,蹒跚；犹豫不决,,
teetotalism,禁酒,,
telling,有效的；显著的,,
temerity,鲁莽,,
temporize,行动躲躲闪闪以争取时间、躲避争论等,,顺应时势
tempestuous,突然的，剧烈的,暴风雨的,
tenable,无懈可击的；有据可依的,,
tendentious,有偏见的,,
tenuous,没有实际内容的，空洞的,inane,
terse,简洁的,,
testy,易怒的,,
tether,栓；系；束缚；能力忍耐力的极限,,
theatrical,做作的；夸张的,戏剧的,
threadbare,陈腐的；贫穷的；破烂的,,
throng,大量聚集,,
ticklish,易怒的；棘手的对技巧要求高的,,
tiff,小争吵,squabble,
tightfisted,吝啬的,stingy,
timorous,胆小的,,
tinge,给…着上少量的色彩,,
tinker,乱修乱调整、修补,,
tint,涂浅色；微染,,
tirade,暴风雨的,,
toady,马屁精,sycophant,
tonic,滋补的；有益健康的,补药,
`,
//list 26
`
topsy-turvy,混乱的,welter,
torpid,麻木的；迟钝的行动迟缓的,,
torpor,缺乏兴趣；迟钝懒散,,
torrential,急流的,,
torrid,酷热的；热情的，感情深厚的,,
tortuous,拐弯抹角的,,
tout,极力赞扬,,
transfigure,改观,,
transgress,违犯,做坏事,
translucent,半透明的；透明的,,
travail,辛苦劳动,,
treacherous,背叛的,,
trenchant,锐利的；犀利的一针见血的,,
trepidation,恐惧,,
trespass,非法侵入；违反冒犯,,
trickle,一滴滴地流,,
trite,陈腐的,,
truant,逃避责任的,,
truce,休战,,
truculent,尖酸刻薄的；好斗的,,
trudge,吃力而笨拙地走,,
trumpet,大声说出或宣告,,
truss,系紧 扎紧,,
tumult,骚动 ,,
turgid,浮夸的,,
turncoat,叛徒,,
turpitude,卑鄙,,
twig,了解,,
tyro,新手；业余爱好者,,
unassailable,无可争辩的，无可亵渎的,,
uncanny,离奇的,可怕的,
uncouth,粗俗的,,
unctuous,油嘴滑舌的；夸张做作的,,
underdog,受害者，输家,,
undergird,加强,gird束缚,
understated,朴素的；不惹眼的,,
understudy,替补演员,,
unexceptionable,无懈可击的,完全满意的,
unflappable,镇定的,,
ungainly,笨拙的,,
unimpeachable,无可置疑的,无可指责的,
unkempt,凌乱无序的,,
unrequited,无报答的；无报酬的,,
unruly,难驾驭的,,
untenable,防守不住的,tenable站得住脚的、可维持的,
untold,数不清的,,
untoward,不吉利的；难以驾驭的,,unruly
unwitting,不知道的未察觉的；偶然的,,
unwonted,不寻常的,,
upbraid,谴责,,
usurp,篡夺；篡位,,
vacuous,愚蠢的,,
vagary,奇想、奇特行为,,
valediction,告别；告别词,,
valiant,勇敢的,,
vanquish,征服,,
vapid,无趣的,,
variegated,杂色的 斑驳的,,
varnish,上清漆；粉饰,光亮漆,
vault,跳跃；一跃而至,,
vaunt,吹嘘,,
veer,转向；改变航线,,
vehement,热情的；感情强烈的,,
venal,贪污受贿的,,
veneer,薄木板，用以贴在家具外面的饰面板；粉饰,,
venial,可宽恕的,,
venom,毒液；恶意,,
`,
//list 27
`
veracious,诚实的；准确的,,
verbatim,逐字的，一字不差的,完全按照字面意思的,
verbose,冗长的,,
verdant,翠绿的郁郁葱葱的,,
verisimilar,好像真实的,,
veritable,真正的,,
vernacular,方言；非正式的口头的,,
versatile,多才多艺的全能的；易改变的,,
verse,使精通；诗歌,,
vertigo,眩晕,,
verve,活力热情,vim,
vestige,微小的遗迹；小痕迹,,
vestigial,发育不全的、退化的,,
veteran,老兵；有丰富经验的人；经验丰富的,,
veto,否决,,
vicarious,代理的、取代的,,
vicissitude,自然变化、变迁兴衰,,
victimize,使受骗；牺牲,,
vigilant,警醒的、警惕的,,
vignette,简介、短文,,
vim,活力,verve,
vindictive,复仇的,,
virtuoso,艺术鉴赏家 专家；技艺精湛的,,
virtuous,品德高尚的、正直的,,
virulent,有毒的，凶残的,,
viscid,有粘性的,,
viscous,粘稠的 粘的,,
vitiate,削弱损害；降低堕落,,
vitriolic,刻薄的,,
vituperate,谩骂、辱骂,,
volition,意志、抉择,,
voluminous,卷数多的；大量的,,
voluptuous,奢侈淫乐的,sybarite,
voracious,有很大食欲的；贪婪的,,
votary,崇拜者,,
vouch,担保 声称为真,,
vulgar,粗俗的；口头的非正式的,vernacular,
waddle,摇摇摆摆地走,,
waffle,胡扯,,
waft,飘荡,,
wag,诙谐幽默的人；摆动,,
wan,苍白的；病态的,,
wanderlust,旅行癖、漫游癖,,
wane,减少,,
warmonger,好战者,monger 贩子,
warp,使偏向；扭曲变形；曲解,,
wary,小心的；机警的,,
wastrel,败家子,,
watershed,转折点，重要关头,,
wax,增大；月亮渐满；上光,,
waylay,伏击；埋伏,,
welter,混乱动乱,,
wheedle,哄骗,,
whet,磨快、引起、刺激,,
whiff,微风；细微信号痕迹,,
whimsical,反复无常的,,
wholesome,有益身心健康的；卫生的,,
wickedness,邪恶,,
wince,畏缩,,
windbag,健谈的人,,
winsome,迷人的,,
wither,枯萎,,
withhold,扣压、抑制,,
wizen,凋谢；枯萎的,sere,
wobble,摇晃；犹豫不决,waddle 摇摆的走,
worldly,世俗的；老练的,,
wrangle,纷争争端；争吵,,
wretched,沮丧的；极差的,,
wry,扭曲的；坚持错误的,,
xenophobe,仇视或畏惧外国人者,,
yoke,连接,,
yokel,天真淳朴的人，乡下人,,
zesty,刺激的开胃的,,
`,
//list 28
`
ravenous,食量大的、贪食的,gluttonous/rapacious,
simile,明喻,,
nirvana,彻底放松的状态,天堂、极乐世界,
ferocious,极端的、剧烈的,爆发性的、凶残的,
affix,粘合,,
pious,虔诚的devout,忠诚的,
obsolete,过时的、被淘汰的,moth-eaten,
wiretap,窃听,eavesdrop,
surveillance,监视、监控,,
renege,放弃、摒弃,abnegate/recant/renounce/repeal,
rigmarole,混乱而无意义的话 babble/drivel/gabble/gibber/jabber,,
pivotal,最关键重要的,,
unavailing,徒劳的、无果的,bootless,
cachet,威望、声望,kudos,
graft,移植、移接,,
feisty,好斗的、好争论的,,
cascade,小瀑布,cataract大瀑布,
vile,丑陋的grotesque/hideous,卑鄙的,
poach,水煮,偷猎,
palpitation,有节奏的舒张收缩,心悸、跳动,
palaver,对话、交流colloquy,闲聊,
overwrought,激动不安的,过分华丽的,
sequel,结果,,
fad,(短暂的)流行、时尚,,
avowal,承认,repudiate否认,
backfire,事与愿违、发生意外,,
baffle,挫败、阻挠,使疑惑,
careen,倾斜,猛冲、狂奔,
constrict,压缩、压紧,,
debonair,无忧虑的、不在乎的,风度翩翩的,
hobble,跛行、蹒跚falter/limp/stagger/totter,,阻碍
plush,(味道)浓郁的,奢华的,
rhetorical,语言上的、言辞华丽（却无内涵的）,,lexical
夸夸其谈的 bombastic/flatulent/florid/gassy/grandiloquent,,,
thick-skinned,冷漠无情的、不顾他人感受的,,
trifle,不重要的事,玩弄dally,trifling不重要的
weather,经受得住、安全度过,,
wily,狡猾的 cagey/craft/cunning/devious/guileful,,
convene,召开、召集,聚集、集合,
demotion,降职、降级,,
glower,怒目而视 scowl,,
grit,毅力、咬紧牙关,,
infraction,违背、违反,,
madcap,热爱冒险的人,大胆的、鲁莽的 audacious/bold/brash/daredevil/reckless,
大量,bundle/myriad/profusion/scads,,
stasis,平衡、停滞,,
tycoon,大亨、巨头,,
umbrage,不悦、生气,,
wilt,萎蔫,,
agape,急切盼望的 agog,,
annex,附属建筑、裙楼,添加、合并,吞并、夺取
baffling,令人疑惑、难以理解的,,
bewitching,迷人的,,
bumble,含糊不清、杂乱无章的说,笨拙的行动,
chaperone,同行、护送,,
charisma,魅力、吸引力,,
conflagration,大火 inferno,武装冲突、战争,
crow,感到高兴 exuberate/jubilate,自鸣得意brag/swagger/vaunt,
dashing,爱好冒险的、大胆的, craven/pusillanimous/timorous,
deplorable,卑鄙可耻的despicable/grubby/paltry,悲惨的,
dike,堤坝,水沟、水渠 ditch/gutter/trench,
escort,护卫队,同行/护送,
felony,重罪,轻罪 peccadillo,
grumble,低声抱怨 carp/fuss/gripe/grouch/grouse/grump/moan/repine,,
heckle,起哄、使难堪badger/bait,,
lance,长毛、标枪,刺破,
rampant,生长茂盛的lush,猖獗不受限的,
remnant,残余、剩余物,,
`,
//list 29
`
willy-nilly,不论是否愿意的,慌乱的、随意的,,
belligerence,好斗、好战,·,,
disenchanted,清醒地,,,
forage,寻找,,,
plebeian,平民的、社会下层的,vulgar,,
squeamish,恶心的,晕船的,,
wrest,拧、扭动,辛苦的获得,,
imposter,冒名顶替者,骗子,,
incumbent,义不容辞的、必须的,,,
splinter,尖细条、刺,切成细条,splint 薄木条,
commiserate,怜悯、同情,condole,,
nullification,(法律条文)废除、废弃,,,
behoove,对。。有利的,beseem,,
defray,支付disburse,,,
machination,诡计,,,
onset,攻击、进攻onslaught,起始、开始,,
canonize,过分宠爱、过分崇拜,使。。崇高、神圣,,
fitful,无规律的、缺乏周期的,,,
oaf,呆子、白痴dolt/dupe/moron,畸形儿,,
retentive,记性好的,反：oblivious,,
secede,脱离、退出(组织、团体),,,
glacial,冰冷的、冰河时代的,冷漠的 ,,
pedagogical,教学的、教师的,,,
perilous,危险的、冒险的 grave/jeopardizing,,,
affliction,痛苦、悲伤、折磨,,,
frosty,寒冷的 algid/glacial,无感情的、冷淡的,,
sacrosanct,神圣不可侵犯的,反 profane,,
shifty,狡诈的、欺诈的,,,
topsy-turvy,混乱的、不整洁的,,,
wayward,刚愎自用的、不服管束的,balky/contumacious/obstreperous,,
backslide,倒退、滑坡、故态复萌,retrograde/retrogress,,
beholden,欠他人人情的、蒙恩的,,,
beige,缺乏特征的,米黄色浅褐色的,,
ill-bred,没教养、没礼貌的,,,
menial,仆人、奴仆,卑贱的、低下的servile/slavish,,
peculiarity,特征、特点,,,
idiosyncrasy,怪癖quirk,,,
coy,故作羞涩的,不愿与人交往的、内向的bashful,,
staunch,忠诚的、坚定的,,,
atrophy,萎缩、衰退,,,
splutter,急切而不清楚的说,,,
vouchsafe,允诺、给予,,,
deadlock,僵局,,,
groggy,虚弱的、走路不稳的,无法思考头脑不清的,,
anachronistic,时代错误的,,,
antedate,比。。早、早于,,,
bogus,伪造的、假冒的,虚伪做作的,,
brandish,挥舞、炫耀,,,
deflect,使偏斜、使转向,,,
erroneous,错误的,,,
fleeting,稍纵即逝的、短暂的,,,
foreground,强调、重视,,,
gawky,笨拙的,名 gawkiness,,
indecorous,不合礼节的、不得体的,反 felicitous,decorous 礼貌的、高雅的,
lax,松弛的、不紧的、不严格的,懈怠的、漫不经心的,,
lurid,恐怖的、令人反感的,苍白的、病态的pallid/wan,,
malignant,恶毒的、邪恶的atrocious/malevolent/malicious/malign/nasty,,,
notoriety,臭名,,,
overshadow,使变暗淡,超越、超过,,
pragmatic,实用主义的、务实的,,,
skittish,易受惊吓的、胆小的 timorous/tremulous,,容易激动的,善变的、多变的
abreast,并排的,熟知的,,
`,
//list 30
`
affectation,虚伪、做作,mannerism
antithetical,完全对立的、相反的,
apparition,鬼魂、幽灵,
assail,抨击,猛攻
attune,使协调、使和谐,
auspicious,好兆头的,ominous凶兆的
bask,休息、悠然自得,
belligerent,好斗的,agonistic/feisty/gladiatorial
beset ,使苦恼、骚扰,攻击
blackmail,敲诈、勒索,
bluff,直截了当的brusque,欺骗
brim,边缘fringe/periphery,充满、加满、倒满
calamity,大灾难apocalypse/cataclysm,
captious,吹毛求疵的,
cellular,多孔的,porous
ceremonious,讲究礼节的、庄重地,
certitude,确信无疑的,
chivalrous,有骑士风度的、彬彬有礼的,
chorale,赞美诗、合唱班,
clan,团体、帮派,clannish 派系的、团结的
cleave,紧贴、坚持,分隔、割裂
conflate,混合,
consign,转交、转移,
consternation,惊愕、恐慌,
contempt,蔑视、鄙视,
contend,竞争、争夺,声称、声明
decry,强烈反对、否定,
deign,屈尊、俯就,
delineate,勾勒、用线条描绘,描写、描绘
drab,单调的、无聊的,
eclectic,混合的、多元化的,
enamored,迷恋的、热爱的bewitched,
enthrall,(魔咒般的)吸引,enchant/engross
ethos,道德准则,
exorcise,除去,
explicate,解释、说明,
extrapolate,(通过逻辑)推断,
fallible,可能出错的,
`,
//list 31
`
figment,虚构的事物、幻觉,,
forebode,预示、预兆,augur,
forsake,彻底放弃、抛弃,,
germinate,发芽,出现,
grudge,怨恨、不满,,
humdrum,千篇一律、单调,无聊乏味的arid/jading,
hypothetical,假设、前提条件,假定的,
impunity,免责、免受处罚,,
ludicrous,荒唐可笑的,,
malevolent,恶意的、恶毒的,,
meretricious,俗艳的garish/gaudy/ostentatious/tawdry,,
milieu,环境、氛围,,
nostalgia,思乡之情,怀旧、怀念,
ordeal,严峻的考验,,
ostensible,表面上的、佯装的,,
outgrowth,结果、后果,,
outmoded,过时的、废弃的,,
override,不顾,,
panacea,万能药,,
prequisite,额外的好处,,
petulant,易怒的、爱发脾气的,,
prerogative,特权、权力,,
proprietary,所有权,私营的,
redeem,实践、履行(诺言),改过自新,
restitution,补偿、赔偿,,
resurrect,使重生、使复苏,,
reverberate,回荡、回想,,
ruthless,没有同情心的、残忍的,,
scourge,祸害,,
scruple,(良心)不安,,
sectarianism,宗派主义、顽固,,
secular,世俗的、尘世的 carnal/mundane,,
succumb,屈服,死亡,
supersede,取代、替代,,
surly,脾气不好的,,
surmise,推测、揣测,,
surrogate,替代品,,
teeming,大量的,,
unanimous,一致同意的,,
voyeur,淫窥狂,voyeurism 偷窥癖,
willful,固执倔强的 mulish/obdurate,,故意的
wistful,渴望的、怀念的,,
`
];

export default words
