const words = [
`
fussy ,谨慎的,过分雕琢的,挑剔的,
fusty,过时的,腐臭的 malodorous/ fetid/ effluvium,,
futile,无效的、无用的,不严肃的 flighty/frivolous/frothy,,
gadfly,刺激物、令人反感的人,,,
gaffe,失礼、失态,明显的过失错误 blunder,,
gainsay,否认,反对,,
gall,激怒,敌意 animosity/animus,大胆、无耻 audacity/brass,
gallant,应用的,高贵的、慷慨的,,
galvanize,刺激,,,
`,
`
gambol,欢跳、雀跃 ,cavort,,
gangly,身材瘦长的,,,
garble ,曲解、篡改,筛选、除杂,adulterate 掺杂,
gargantuan,巨大的,,,
garish,过于鲜艳张扬的,俗不可耐的,,
garment,衣服 apparel,,,
garrulous,啰嗦的，话多的,loquacious/ voluble,garrulity,
gash,深长的伤口,划伤、戳破,,
gasification,气化,,,
gauche,笨拙的、不善交际的,,,
`,
`
gaudy,俗艳的 garish,,,
gauge,测量标准,判定,,
gear,调整（以配合）,,,
genial,和蔼可亲的 ,热心友好的 amicable,温暖的,
genteel,有教养的、不粗俗的,,,
germane,有关的、适当的,,,
gibe,嘲弄 deride,,,
giddy,轻浮不严肃的 ,frivolous/ frothy,喜悦的 elated/euphoric,
gild,做多余的修饰,镀上金子的色彩,,
gist,要点,,,
`,
`
gladiator,角斗士,争论者,,
glaze,给。。上釉、妆点,使平滑,,
glib ,流利圆滑的,肤浅的,,
glisten,闪光,,,
glitch,小故障,,,
gloat,自鸣得意,,,
gloss,简短解释,（欺骗性的）光鲜外表,敷衍了事,开脱罪名
glossy,光滑的、有光泽的,burnished,,
glut,使过量、使充满,,,
`,
`
glutinous ,胶状的、粘的,,,
glutton,酷爱。。的人,贪吃人 gorger,gluttony 暴饮暴食,
goad,刺激驱使、激发,,,
gobble,狼吞虎咽,devour/ gorge（也有‘峡谷’之意）,nibble 小口咬,
gourmand,大胃王、嗜食者,,,
goggle,凝视,,,
goldbrick,逃避工作和责任,,,
gossamer,虚无缥缈的东西,轻薄的 diaphanous/ethereal,,
gourmet,美食家 connoisseur/epicure,,,
`,
`
grandeur,高尚、重要,the glory that was Greece and the grandeur that was Rome,,
grandiloquent ,(言语）浮夸的,,,
grandstand,哗众取众、为博取喝彩而卖弄,,看台,
grate,刮擦（发出刺耳声）,骚扰、惹恼 peeve,grating 刺耳的,
gratuitous,无根据的, 不必要的多余的dispensable,免费的、无报酬的,
gregarious,爱社交的 convivial/extroverted/genial,,群居的,
`
];

export default words
